# Generated by Django 3.2.5 on 2021-07-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publicaiton_date',
            new_name='publication_date',
        ),
    ]
